name: PR
on: pull_request
jobs:
  build-test:
    #버전별 테스트 방법
    strategy:
      matrix:
        node-version: [18, 20]
    runs-on: ubuntu-latest
    steps: 
      - name: Get Codes
        uses: actions/checkout@v4

      #node.js 설치
      - name: Install NodeJs
        uses: actions/setup-node@v4

      - name: Install Deps
        run: npm install
        
      - name: Build
        run: npm run build